#include <riscv/sim.h>
#include <riscv/processor.h>
#include <riscv/devices.h>
#include <riscv/cfg.h>
#include <riscv/disasm.h>
#include <riscv/decode.h>
#include <riscv/mmu.h>
#include <riscv/vector_unit.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <vector>
#include <string>
#include <memory>
#include <iostream>
#include <iomanip>
#include <fstream>
#include <map>
#include <cstdint>

namespace py = pybind11;

/**
 * @enum XLen
 * @brief Specifies the register width (bit-width) of the RISC-V target
 */
enum class XLen {
    XLEN_32 = 32,   ///< 32-bit RISC-V (RV32*)
    XLEN_64 = 64    ///< 64-bit RISC-V (RV64*)
};

/**
 * @class SpikeBridge
 * @brief High-performance wrapper around the Spike RISC-V ISA simulator
 * 
 * This class encapsulates all Spike simulator interactions, providing a clean
 * interface for Python through Pybind11. It dynamically configures Spike based
 * on the provided ISA string and supports both 32-bit and 64-bit targets.
 * 
 * Design Principles:
 * - Single simulation instance per SpikeBridge object (persistent state)
 * - Type-safe register access using appropriate C++ types (uint32_t for RV32, uint64_t for RV64)
 * - Modular memory interface supporting ELF and hex file loading
 * - Comprehensive error handling with Python exception propagation
 */
class SpikeBridge {
private:
    XLen xlen;                          ///< Register width (32 or 64 bits)
    std::unique_ptr<cfg_t> cfg;         ///< Spike configuration object
    sim_t *sim;                         ///< Spike simulator instance
    processor_t *cpu;                   ///< Primary CPU core
    std::string isa_string;             ///< ISA configuration string (e.g., "rv64gcv_zba_zbb_zbs_zicond_zfa_zcb")

    /**
     * @brief Determine XLEN from ISA string
     * @param isa The ISA configuration string
     * @return XLen::XLEN_32 or XLen::XLEN_64
     * @throws std::invalid_argument if ISA string is malformed
     */
    XLen detect_xlen(const std::string& isa) const {
        if (isa.find("rv32") != std::string::npos || isa.find("RV32") != std::string::npos) {
            return XLen::XLEN_32;
        } else if (isa.find("rv64") != std::string::npos || isa.find("RV64") != std::string::npos) {
            return XLen::XLEN_64;
        } else {
            throw std::invalid_argument(
                "[ERROR] ISA string must contain either 'rv32' or 'rv64'. Got: " + isa
            );
        }
    }

    /**
     * @brief Load program memory from a Verilog hex file
     * 
     * Hex file format:
     *   @ADDRESS_HEX
     *   BYTE1 BYTE2 BYTE3 ...
     *   @NEXT_ADDRESS
     *   ...
     * 
     * @param path Path to the hex file (typically generated by objcopy -O verilog)
     */
    void load_hex(const std::string& path) {
        std::ifstream file(path);
        if (!file.is_open()) {
            std::cerr << "[ERROR] Could not open hex file: " << path << std::endl;
            throw std::runtime_error("[ERROR] Hex file not found: " + path);
        }

        std::string word;
        uint64_t current_addr = 0;
        auto mmu = sim->get_core(0)->get_mmu();

        while (file >> word) {
            if (word[0] == '@') {
                // Set new base address (e.g., @80000000)
                current_addr = std::stoull(word.substr(1), nullptr, 16);
            } else {
                // Read one byte (e.g., "81")
                uint8_t byte_val = (uint8_t)std::stoul(word, nullptr, 16);

                // Store 1 byte at a time
                // This is safe and correctly handles Little-Endian
                // because the .hex file is already ordered byte-by-byte
                mmu->store<uint8_t>(current_addr, byte_val);
                current_addr++;
            }
        }
        std::cout << "[C++] Loaded HEX: " << path << " into simulation memory." << std::endl;
    }

    /**
     * @brief Initialize Spike configuration based on ISA and XLEN
     */
    void configure_memory_layout() {
        cfg->mem_layout = {
            mem_cfg_t(0x00001000, 0x1000),     // BootROM (4 KB)
            mem_cfg_t(0x80000000, 0x1000000)   // RAM (16 MB)
        };
    }

public:
    /**
     * @brief Construct a SpikeBridge for a specific ISA and program
     * 
     * @param program Base name of the program (without extension)
     *                Expects files: program.elf and program.hex
     * @param isa ISA configuration string (e.g., "rv32imac", "rv64gcv_zba_zbb_zbs_zicond_zfa_zcb")
     *            Must contain either "rv32" or "rv64"
     * 
     * @throws std::invalid_argument if ISA string is malformed
     * @throws std::runtime_error if ELF/hex files cannot be loaded
     * @throws std::exception for other Spike initialization errors
     */
    SpikeBridge(const char* program, const char* isa = "rv64gcv_zba_zbb_zbs_zicond_zfa_zcb") {
        try {
            std::string program_str(program);
            isa_string = std::string(isa);

            // ============================================================
            // 1. Detect XLEN from ISA string
            // ============================================================
            xlen = detect_xlen(isa_string);
            std::cout << "[C++] Detected XLEN: " << static_cast<int>(xlen) << " bits" << std::endl;
            std::cout << "[C++] ISA: " << isa_string << std::endl;

            // ============================================================
            // 2. Initialize Spike configuration
            // ============================================================
            cfg = std::make_unique<cfg_t>();
            cfg->isa = isa_string.c_str();
            configure_memory_layout();

            // ============================================================
            // 3. Create memory objects
            // ============================================================
            auto boot_mem = std::make_shared<mem_t>(0x1000);      // 4 KB BootROM
            auto ram_mem = std::make_shared<mem_t>(0x1000000);    // 16 MB RAM

            // Register memory regions with Spike
            std::vector<std::pair<reg_t, abstract_mem_t*>> mems;
            mems.push_back(std::make_pair(reg_t(0x00001000), boot_mem.get()));
            mems.push_back(std::make_pair(reg_t(0x80000000), ram_mem.get()));

            // ============================================================
            // 4. Prepare HTIF arguments and plugin devices
            // ============================================================
            std::string elf_path = program_str + ".elf";
            std::vector<std::string> htif_args = { elf_path };
            std::vector<std::pair<const device_factory_t*, std::vector<std::string>>> plugin_devices;

            std::cout << "[C++] Initializing sim_t with: " << elf_path << std::endl;

            // ============================================================
            // 5. Construct Spike simulator
            // ============================================================
            sim = new sim_t(
                cfg.get(), 
                false,                              // debug_mode
                mems,                               // memory regions
                plugin_devices,                     // plugins
                false,                              // require_isa_check
                htif_args,                          // host interface args
                debug_module_config_t(),            // debug config
                nullptr,                            // custom device factory
                false,                              // log_commits
                nullptr,                            // log_file
                false,                              // socket_log
                stdout,                             // output stream
                std::nullopt                        // seed
            );

            // Add memory devices to Spike's internal mapping
            sim->add_device(0x00001000, boot_mem);
            sim->add_device(0x80000000, ram_mem);

            // ============================================================
            // 6. Configure vector unit (if enabled in ISA)
            // ============================================================
            for (size_t i = 0; i < sim->nprocs(); i++) {
                sim->get_core(i)->VU.VLEN = 256;   // VLEN in bits (adjustable)
                sim->get_core(i)->VU.ELEN = 64;    // ELEN in bits (adjustable)
            }

            // ============================================================
            // 7. Load program into memory
            // ============================================================
            std::string hex_path = program_str + ".hex";
            load_hex(hex_path);

            // ============================================================
            // 8. Cache CPU reference
            // ============================================================
            cpu = sim->get_core(0);
            auto state = cpu->get_state();

            // ============================================================
            // 9. Print Privilege/Memory Configuration
            // ============================================================
            std::cout << "\n" << std::string(58, '=') << std::endl;
            std::cout << "[DEBUG C++] Privilege CSR PMP/MMU Configuration:" << std::endl;
            std::cout << "  Privilege Mode: " << (int)state->prv << " (3=M, 1=S, 0=U)" << std::endl;

            if (state->csrmap.count(0x3A0)) {
                uint64_t cfg0 = state->csrmap[0x3A0]->read();
                std::cout << "  CSR pmpcfg0 (0x3A0): 0x" << std::hex << cfg0 << std::dec << std::endl;
            }

            for (int i = 0; i < 4; i++) {
                uint64_t addr_val = state->pmpaddr[i]->read();
                std::cout << "  CSR pmpaddr" << i << ": 0x" << std::hex << addr_val << std::dec << std::endl;
            }

            if (state->csrmap.count(0x180)) {
                uint64_t satp = state->csrmap[0x180]->read();
                std::cout << "  CSR satp (0x180): 0x" << std::hex << satp << std::dec 
                         << " (0=Bare Mode)" << std::endl;
            }
            std::cout << std::string(58, '=') << "\n" << std::endl;

            std::cout << "[C++] Core starts at PC: 0x" << std::hex << cpu->get_state()->pc 
                     << std::dec << std::endl;

        } catch (std::exception& e) {
            std::cerr << "[C++ CRITICAL ERROR]: " << e.what() << std::endl;
            throw;
        } catch (...) {
            std::cerr << "[C++ CRITICAL ERROR]: Unknown error in SpikeBridge constructor!" << std::endl;
            throw;
        }
    }

    /**
     * @brief Get the XLEN (register width) of this target
     * @return 32 or 64
     */
    int get_xlen() const {
        return static_cast<int>(xlen);
    }

    /**
     * @brief Get the ISA string used for this simulation
     */
    std::string get_isa() const {
        return isa_string;
    }

    /**
     * @brief Dump memory contents for debugging
     * @param start_addr Starting address
     * @param count Number of 32-bit words to dump
     */
    void dump_memory(reg_t start_addr, size_t count) {
        auto core = sim->get_core(0);
        auto mmu = core->get_mmu();

        std::cout << std::string(58, '=') << std::endl;
        std::cout << "[DEBUG C++] Dump memory from 0x" << std::hex << start_addr
                << " (" << std::dec << count << " 32-bit words):" << std::endl;

        for (size_t i = 0; i < count; i++) {
            reg_t current_addr = start_addr + (i * 4);
            try {
                uint32_t val = mmu->load<uint32_t>(current_addr);
                printf("  0x%08lx:  %08x\n", (unsigned long)current_addr, val);
            } catch (trap_t& t) {
                printf("  0x%08lx:  [ERROR] Trap: %s\n", (unsigned long)current_addr, t.name());
            } catch (...) {
                printf("  0x%08lx:  [ERROR] Access failed\n", (unsigned long)current_addr);
            }
        }
        std::cout << std::string(58, '=') << "\n" << std::endl;
    }

    /**
     * @brief Execute one instruction
     * @throws std::runtime_error on RISC-V traps or execution errors
     */
    void step() {
        try {
            cpu->step(1);
        } catch (trap_t& t) {
            throw std::runtime_error("Trap ID: " + std::to_string(t.cause()));
        } catch (std::exception& e) {
            throw std::runtime_error(e.what());
        }
    }

    /**
     * @brief Get disassembly of the instruction at the current PC
     * @return Disassembled instruction string
     */
    std::string get_disasm() {
        uint64_t pc = cpu->get_state()->pc;
        try {
            auto fetch = cpu->get_mmu()->load_insn(pc);
            return cpu->get_disassembler()->disassemble(fetch.insn);
        } catch (trap_instruction_access_fault& t) {
            return "ERROR: Instruction Access Fault (PMP/MMU block)";
        } catch (...) {
            return "ERROR: Unknown Fetch Error";
        }
    }

    /**
     * @brief Get Program Counter
     * @return PC value (always as uint64_t, but only lower bits are significant for RV32)
     */
    uint64_t get_pc() {
        return cpu->get_state()->pc;
    }

    /**
     * @brief Get General Purpose Register (XLEN-aware)
     * 
     * For RV32: Returns only the lower 32 bits
     * For RV64: Returns full 64-bit value
     * 
     * @param i Register index (0-31)
     * @return Register value
     */
    uint64_t get_reg(int i) {
        if (i < 0 || i >= 32) return 0;
        
        uint64_t val = cpu->get_state()->XPR[i];
        
        // For RV32, sign-extend to 64 bits (Spike stores as 64-bit internally)
        // This is handled transparently by Spike, but we mask for safety
        if (xlen == XLen::XLEN_32) {
            val = (int32_t)val;  // Sign-extend
        }
        
        return val;
    }

    /**
     * @brief Get Floating Point Register
     * 
     * @param i FPR index (0-31)
     * @return 64-bit floating point register value
     */
    uint64_t get_fp_reg(int i) {
        if (i < 0 || i >= 32) return 0;
        return cpu->get_state()->FPR[i].v[0];
    }

    /**
     * @brief Get Vector Register as byte array
     * 
     * @param i Vector register index (0-31)
     * @return Vector of bytes representing the entire register
     */
    std::vector<uint8_t> get_vec_reg(int i) {
        std::vector<uint8_t> reg_data;
        if (i < 0 || i >= 32 || !sim->get_core(0)) return reg_data;

        size_t vlenb = sim->get_core(0)->VU.vlenb;
        reg_data.resize(vlenb);

        uint8_t* start_ptr = (uint8_t*)sim->get_core(0)->VU.reg_file + (i * vlenb);
        std::copy(start_ptr, start_ptr + vlenb, reg_data.begin());

        return reg_data;
    }

    /**
     * @brief Get Vector Length in bits
     */
    size_t get_vlen() {
        if (sim && sim->get_core(0)) {
            return sim->get_core(0)->VU.get_vlen();
        }
        return 0;
    }

    /**
     * @brief Get Element Length in bits
     */
    size_t get_elen() {
        if (sim && sim->get_core(0)) {
            return sim->get_core(0)->VU.get_elen();
        }
        return 0;
    }

    /**
     * @brief Set Machine External Interrupt
     * 
     * @param high true to assert interrupt, false to deassert
     */
    void set_interrupt(bool high) {
        if (high) {
            cpu->get_state()->mip->write_with_mask(MIP_MEIP, MIP_MEIP);
        } else {
            cpu->get_state()->mip->write_with_mask(MIP_MEIP, 0);
        }
    }

    /**
     * @brief Get all active Control and Status Registers
     * 
     * Returns a map of CSR address (as int) to value (as int).
     * For RV32, values are 32-bit. For RV64, values are 64-bit.
     * 
     * @return std::map<int, uint64_t> CSR address -> value
     */
    std::map<int, uint64_t> get_csrs() {
        std::map<int, uint64_t> csr_snapshot;
        auto core = sim->get_core(0);
        auto& csrmap = core->get_state()->csrmap;

        for (auto const& [addr, csr_ptr] : csrmap) {
            try {
                uint64_t val = csr_ptr->read();
                // For RV32, mask to 32 bits
                if (xlen == XLen::XLEN_32) {
                    val = (uint32_t)val;
                }
                
                csr_snapshot[addr] = val;
            } catch (...) {
                // Skip CSRs that trap on read
                continue;
            }
        }
        return csr_snapshot;
    }

    /**
     * @brief Destructor: clean up Spike simulator
     */
    ~SpikeBridge() {
        delete sim;
    }
};

// ============================================================================
// Pybind11 Module Definition
// ============================================================================

PYBIND11_MODULE(spike_py, m) {
    m.doc() = "RISC-V Spike Simulator Python Wrapper (32-bit and 64-bit support)";

    // Expose XLen enum
    py::enum_<XLen>(m, "XLen")
        .value("XLEN_32", XLen::XLEN_32)
        .value("XLEN_64", XLen::XLEN_64);

    // Expose SpikeBridge class
    py::class_<SpikeBridge>(m, "SpikeBridge")
        .def(py::init<const char*, const char*>(), 
             py::arg("program"), 
             py::arg("isa") = "rv64gcv_zba_zbb_zbs_zicond_zfa_zcb",
             "Construct SpikeBridge for a given program and ISA")
        
        // Configuration queries
        .def("get_xlen", &SpikeBridge::get_xlen,
             "Get register width (32 or 64 bits)")
        .def("get_isa", &SpikeBridge::get_isa,
             "Get ISA configuration string")
        
        // Execution control
        .def("step", &SpikeBridge::step,
             "Execute one instruction")
        
        // Register access (XLEN-aware)
        .def("get_pc", &SpikeBridge::get_pc,
             "Get Program Counter")
        .def("get_reg", &SpikeBridge::get_reg, py::arg("index"),
             "Get General Purpose Register")
        .def("get_fp_reg", &SpikeBridge::get_fp_reg, py::arg("index"),
             "Get Floating Point Register")

        // Vector register access
        .def("get_vec_reg", &SpikeBridge::get_vec_reg, py::arg("index"),
             "Get Vector Register as byte array")
        .def("get_vlen", &SpikeBridge::get_vlen,
             "Get Vector Length in bits")
        .def("get_elen", &SpikeBridge::get_elen,
             "Get Element Length in bits")
        
        // Disassembly and state
        .def("get_disasm", &SpikeBridge::get_disasm,
             "Get disassembly of instruction at current PC")
        .def("get_csrs", &SpikeBridge::get_csrs,
             "Get all active Control and Status Registers")
        
        // Debugging utilities
        .def("dump_memory", &SpikeBridge::dump_memory, 
             py::arg("addr"), py::arg("count"),
             "Dump n 32-bit words starting from addr")
        .def("set_interrupt", &SpikeBridge::set_interrupt, py::arg("high"),
             "Set/clear machine external interrupt");
}
